/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import javax.swing.JPanel;

/**
 *
 * @author chandra
 */
public class GUIConferenceRoom extends javax.swing.JFrame {

    VideoConference vc;
    
    /**
     * Creates new form GUIConferenceRoom
     */
    public GUIConferenceRoom(VideoConference vc) {
        initComponents();
        this.vc = vc;
        buttonQuitRoom.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelVideo1 = new javax.swing.JPanel();
        panelVideo3 = new javax.swing.JPanel();
        panelVideo2 = new javax.swing.JPanel();
        panelVideo4 = new javax.swing.JPanel();
        buttonQuitRoom = new javax.swing.JButton();
        buttonJoinRoom = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listParticipantList = new javax.swing.JList();
        buttonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 241, 204));

        jPanel1.setBackground(new java.awt.Color(255, 249, 204));

        panelVideo1.setBackground(new java.awt.Color(255, 186, 86));
        panelVideo1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panelVideo1.setLayout(new java.awt.BorderLayout());

        panelVideo3.setBackground(new java.awt.Color(255, 186, 86));
        panelVideo3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelVideo3.setLayout(new java.awt.BorderLayout());

        panelVideo2.setBackground(new java.awt.Color(255, 186, 86));
        panelVideo2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panelVideo2.setLayout(new java.awt.BorderLayout());

        panelVideo4.setBackground(new java.awt.Color(255, 186, 86));
        panelVideo4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panelVideo4.setLayout(new java.awt.BorderLayout());

        buttonQuitRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/image/goout.png"))); // NOI18N
        buttonQuitRoom.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonQuitRoom.setBorderPainted(false);
        buttonQuitRoom.setContentAreaFilled(false);
        buttonQuitRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonQuitRoomActionPerformed(evt);
            }
        });

        buttonJoinRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/image/joinla.jpg"))); // NOI18N
        buttonJoinRoom.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonJoinRoom.setBorderPainted(false);
        buttonJoinRoom.setContentAreaFilled(false);
        buttonJoinRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJoinRoomActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel1.setText("Participants List");

        listParticipantList.setBackground(new java.awt.Color(255, 186, 86));
        jScrollPane1.setViewportView(listParticipantList);

        buttonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/image/back.jpg"))); // NOI18N
        buttonBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonBack.setBorderPainted(false);
        buttonBack.setContentAreaFilled(false);
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonBack)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(buttonQuitRoom)
                                        .addComponent(buttonJoinRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelVideo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelVideo3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelVideo2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelVideo4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonJoinRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonQuitRoom))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelVideo3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelVideo4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelVideo2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(panelVideo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonBack)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonJoinRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJoinRoomActionPerformed
        vc.joinRoom();
    }//GEN-LAST:event_buttonJoinRoomActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        vc.showMainGUI();
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonQuitRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonQuitRoomActionPerformed
        vc.quitRoom();
    }//GEN-LAST:event_buttonQuitRoomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonJoinRoom;
    private javax.swing.JButton buttonQuitRoom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listParticipantList;
    private javax.swing.JPanel panelVideo1;
    private javax.swing.JPanel panelVideo2;
    private javax.swing.JPanel panelVideo3;
    private javax.swing.JPanel panelVideo4;
    // End of variables declaration//GEN-END:variables

    public void showVideo1(javax.swing.JComponent c){
        panelVideo1.removeAll();
        panelVideo1.add(c);
        revalidate();
        repaint();
    }
    
    public void showVideo2(javax.swing.JComponent c){
        panelVideo2.removeAll();
        panelVideo2.add(c);
        revalidate();
        repaint();
    }
    
    public void showVideo3(javax.swing.JComponent c){
        panelVideo3.removeAll();
        panelVideo3.add(c);
        revalidate();
        repaint();
    }
    
    public void showVideo4(javax.swing.JComponent c){
        panelVideo4.removeAll();
        panelVideo4.add(c);
        revalidate();
        repaint();
    }
    
    public javax.swing.JPanel getVideo1Panel(){
        return panelVideo1;
    }
    
    public javax.swing.JPanel getVideo2Panel(){
        return panelVideo2;
    }
    
    public JPanel getVideo3Panel() {
        return panelVideo3;
    }

    public JPanel getVideo4Panel() {
        return panelVideo4;
    }
    
    public javax.swing.JList getListRoomParticipantsList(){
        return listParticipantList;
    }

    public javax.swing.JButton getButtonJoinRoom(){
        return buttonJoinRoom;
    }
    
    public javax.swing.JButton getButtonQuitRoom(){
        return buttonQuitRoom;
    }
}
